
Extensi贸n YML:

spring:
 #Configuraci贸n MySQL
  datasource: 
    url: jdbc:mysql://localhost:3306/persona2?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
#Configuraci贸n Creaci贸n de tablas (Hibernate)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
#Que thymeleaf no guarde datos en cache
  thymeleaf:
    cache: false 

